version: "3.8"
services:
  app:
    container_name: bundle-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - phpmyadmin
      - redis
    networks:
      - lion
  redis:
    image: redis
    container_name: bundle-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASES: ${REDIS_DATABASES}
  mysql:
    image: mysql
    container_name: bundle-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lion
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bundle-phpmyadmin
    restart: unless-stopped
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - lion
volumes:
  mysql_data:
  redis_data:
networks:
  lion:
    driver: bridge
